### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by MOshima-PIFSC** [MOshima-PIFSC/NSASS-HTC-HPC-Computing#2]
I just logged into the hera account and noticed that the number in this code is different from what I use (I use -512- compared to -256-). Is this outdated or is this based on user account? If it's user specific we can add a note to clarify.  
https://github.com/MOshima-PIFSC/NSASS-HTC-HPC-Computing/blob/56b322d4feec04d71bedaf66e09dd6c5f1bf589f/assets/hera_documentation.qmd#L19
Also for clarity, what does the -p22 flag do? I don't usually add it when I log in.

**Comment by N-DucharmeBarth-NOAA** [comment]
To answer your first question, 512 vs. 256 this is just a difference in the encryption algorithm used to open the ssh connection. The flag -p22 species opening "port 22" and may be optional.

**Comment by N-DucharmeBarth-NOAA** [comment]
I guess the encryption algorithm is flexible since either one appears to work. However, I'm not sure it is tied to when you generated the ssh key for RDHPCS.
